server.modules = ( "mod_cgi" )
server.document-root = "/opt/broray-light/web-new"
server.bind = "127.0.0.1"
server.port = 8080
server.max-request-size = 5120
server.pid-file = "/opt/broray-light/run/lighttpd.pid"
server.errorlog = "/opt/broray-light/logs/lighttpd-error.log"
index-file.names = ( "index.html" )
mimetype.assign = ( ".html" => "text/html; charset=utf-8", ".css" => "text/css; charset=utf-8", ".js" => "application/javascript; charset=utf-8", ".json" => "application/json; charset=utf-8", ".png" => "image/png", ".ico" => "image/x-icon" )
cgi.assign = ( ".cgi" => "" )
static-file.exclude-extensions = ( ".cgi" )
