#!/opt/bin/ash
BRORAY_BASE="${BRORAY_BASE:-${BRORAY_ROOT:-/opt/broray-light}}"; . "$BRORAY_BASE/lib/util.sh"; . "$BRORAY_BASE/lib/server.sh"
BRORAY_TMP="${BRORAY_TMP:-$BRORAY_BASE/tmp}"; BRORAY_SETTINGS="${BRORAY_SETTINGS:-$BRORAY_BASE/config/system/settings.json}"
broray_generate_server_config(){
 id="$1"; broray_server_exists "$id" || broray_die "сервер $id не найден"; sf="$(broray_server_path "$id")"; broray_server_validate "$sf"; mkdir -p "$BRORAY_TMP"; out="$BRORAY_TMP/config.$id.$$.json"
 socks_port="$(jq -r '.socksPort//2080' "$BRORAY_SETTINGS" 2>/dev/null || echo 2080)"; log_level="$(jq -r '.logLevel//"warning"' "$BRORAY_SETTINGS" 2>/dev/null || echo warning)"
 jq -n --slurpfile s "$sf" --argjson socksPort "$socks_port" --arg logLevel "$log_level" '
 def stream($x): ({network:$x.network,security:$x.security} + (if $x.security=="tls" then {tlsSettings:{serverName:($x.tls.serverName//$x.address),fingerprint:($x.tls.fingerprint//"chrome"),allowInsecure:($x.tls.allowInsecure//false),alpn:($x.tls.alpn//[])}} elif $x.security=="reality" then {realitySettings:{serverName:($x.reality.serverName//$x.address),fingerprint:($x.reality.fingerprint//"chrome"),publicKey:$x.reality.publicKey,shortId:($x.reality.shortId//""),spiderX:($x.reality.spiderX//"")}} else {} end) + (if $x.network=="ws" then {wsSettings:{path:($x.transport.path//"/"),headers:(if (($x.transport.host//"")|length)>0 then {Host:$x.transport.host} else {} end)}} elif $x.network=="grpc" then {grpcSettings:{serviceName:($x.transport.serviceName//"")}} elif $x.network=="httpupgrade" then {httpupgradeSettings:{path:($x.transport.path//"/"),host:($x.transport.host//"")}} elif $x.network=="xhttp" then {xhttpSettings:({path:($x.xhttp.path//"/"),mode:($x.xhttp.mode//"auto")} + (if (($x.xhttp.extra//{})|length)>0 then {extra:$x.xhttp.extra} else {} end))} else {} end));
 ($s[0]) as $x | {log:{loglevel:$logLevel},inbounds:[{tag:"socks-in",listen:"127.0.0.1",port:$socksPort,protocol:"socks",settings:{auth:"noauth",udp:true},sniffing:{enabled:true,destOverride:["http","tls","quic"],routeOnly:true}}],outbounds:[{tag:"proxy",protocol:"vless",settings:{vnext:[{address:$x.address,port:$x.port,users:[{id:$x.uuid,encryption:($x.encryption//"none")}+(if (($x.flow//"")|length)>0 then {flow:$x.flow} else {} end)]}]},streamSettings:stream($x)},{tag:"direct",protocol:"freedom"},{tag:"block",protocol:"blackhole"}],routing:{domainStrategy:"AsIs",rules:[{type:"field",inboundTag:["socks-in"],outboundTag:"proxy"}]}}' > "$out" || broray_die "не удалось сформировать конфигурацию Xray"
 jq -e . "$out" >/dev/null 2>&1 || broray_die "сформирован некорректный JSON Xray"; printf '%s\n' "$out"
}
